apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-openshift
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: eu.gcr.io/labs-athorburn/hello-openshift
          env:
            - name: RESPONSE
              value: "Hello Serverless!"
